My feature
MarvellousUbani/NewYorkTimes pull request #1
Opened 2019-07-16 15:17 UTC by MarvellousUbani

2019-07-16 21:16 UTC, mosaaleb requested changes
## Hi @MarvellousUbani, @Ashah15 :wave:

Good job working on the project so far. :clap:

- [ ] This project is basically to make sure that you fully understand positioning and floats without using `bootstrap`. It's a good point that you are already know how to use bootstrap, but you will have the time to use bootstrap in upcoming projects. So make sure that this project is done without `bootstrap`
- [ ] Let's make sure that we use [stickler](https://github.com/microverseinc/linters-config/tree/master/css). It's much easier now to use, just follow this link. It's important tool that ensure that our code base has no errors, typos, and have healthy style guidelines.
- [ ] Let's add the footer section & social media icons & copyright as seen in the NYT page.
- [ ] Make sure to complete the `readme.md` [properly](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) with `contributors` information section and `about` section or any information you would find relevant.

Let's make sure that these requirements are handled, then please submit a new code review.
Happy coding :computer:

2019-07-17 06:32 UTC, bolah2009 requested changes
# Hi Team :wave: 

Seems this project is still not implemented without using bootstrap as suggested by @mosaaleb 
Fix this and submit a request for another review :+1: 

Feel free to reach out if you have any question.

Keep up the good work and best of luck on the next submission. 👍

Happy Coding!  :dizzy: and Have a Nice Day :smile:

Cheers,  
Bola

2019-07-23 08:17 UTC, bolah2009 requested changes
# Nice Job Team! :clap: 

You've done an awesome Job :muscle:

- A few changes to be made, please check the screenshot below and kindly make changes accordingly. Check the [original site](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html) for more details.

| Current | Preffered |
| :---:   | :---:   |
|  ![btn nyt current](https://user-images.githubusercontent.com/36057474/61695534-8ea6b600-ad2b-11e9-9dd8-bd02c08b7b5e.png) | ![sub login preffered](https://user-images.githubusercontent.com/36057474/61691535-aaa65980-ad23-11e9-82ba-abc27f7eb074.png)  |
| NOT FOUND   | ![read button preffered](https://user-images.githubusercontent.com/36057474/61691720-138dd180-ad24-11e9-8ec0-c4591857c1e6.png)  |
| NOT FOUND  | ![editor's pick ](https://user-images.githubusercontent.com/36057474/61691779-34562700-ad24-11e9-989a-ab37f0c60201.png)  |
| NOT FOUND  | ![sign up](https://user-images.githubusercontent.com/36057474/61691798-4041e900-ad24-11e9-8ec4-8074cbe015dd.png)  |
| NOT FOUND  |  ![nyt popular preffered](https://user-images.githubusercontent.com/36057474/61691978-ae86ab80-ad24-11e9-8bbe-ab3ac2806804.png) |
| NOT FOUND  | ![nyt aside preffered](https://user-images.githubusercontent.com/36057474/61695660-cf063400-ad2b-11e9-82de-e1fe890e5cbe.png) |
| NOT FOUND | ![nyt editor preffered](https://user-images.githubusercontent.com/36057474/61692053-d7a73c00-ad24-11e9-9173-d9bf601331b1.png)  |
| NOT FOUND  | ![nyt footer preffered](https://user-images.githubusercontent.com/36057474/61692215-22c14f00-ad25-11e9-9926-067b71704765.png)  |

You have done an awesome job, consider making these changes, taking into consideration the **positioning and styling** of the above-screenshotted components of the page **including the whole footer section** of the page.

-----

### To make the review even much easier for you, below are the checklist to consider the project `complete`  as it must satisfy the following points:

#### Navigation bar

:heavy_check_mark:   It has a navigation bar

:heavy_check_mark:    It uses the `<nav>` tag

:heavy_check_mark:   It has a "Hamburger button", a search icon and a link with text on the leftmost side of the navbar

:heavy_check_mark:   has the NY Times image logo embedded in the center of the navbar

:recycle:  The NY Times logo is a link

:recycle:   It has both, 'Subscribe' and 'Log in' elements with a `<button>` tag on the rightmost side of navbar

:recycle:    The 'Subscribe' and 'Log in' buttons have a blue background and white letters

#### Bottom
:recycle:   It should have a 'Read comments' button and social media icons (fontawsome is recommended for the icons)

#### Additional Links

:recycle:  The section should be made of two parts: left side for links with images and right for links only

:recycle:    The left side is made of two parts: *More in Space and Cosmos* and *Editor's picks*

#### Footer
:recycle:    It includes the NYTimes logo as an embedded image in the top left corner of the footer

:recycle:  The NYTimes logo is a link

:recycle:  It includes a *go to homepage* link on the top right corner of the footer

:recycle:  The bottom part of the footer to includes links with copyright, TOC, contacts, and help

#### Navigation bar

:recycle:   The Navbar should have a fixed position

:heavy_check_mark:     Floats or flex display for positioning items inside the navbar

#### Main Content
:recycle:      The main content of the website should be wrapped with an HTML tag  `<main>`

:recycle:   The first image should be ~ 50% wider than the rest of the content inside `<main>`

:recycle:   All images and videos should be enclosed by a `<figure>` tag with `<figcaption>` that gives a description of the embedded image or video.

:recycle:   Any sections that include text (paragraphs) should be wrapped with a `<section>` tag 

:recycle:  Include an `<aside>` tag for Editor's picks and a Sign-Up button.

#### Additional Links
:recycle:   The left side uses `<figure>` and `<figcaption>` tags followed by the title of the articles

:heavy_check_mark:    `display: flex` or *float* are recommended

#### Footer
:recycle:     The footer section is wrapped by a `<footer>` tag

:heavy_check_mark:    Links should be organized using the `<ul>` tag and positioned with `display: flex` or *floats*


Keep up the good work and best of luck on the next submission. 👍

Cheers
Bola

2019-07-23 08:17 UTC, bolah2009 commented on index.html
> +
`REQUIRED`

The page is currently missing some section. Please check the original site.

2019-07-23 08:17 UTC, bolah2009 commented on index.html
> +            <p class="cat-title d-inline"><strong>SPACE & COSMOS</strong></p>
`REQUIRED`

Consider wrapping with an anchor tag (`<a>`) as shown below.

![003](https://user-images.githubusercontent.com/36057474/61694450-5e5e1800-ad29-11e9-860f-f1b9b4aca6d7.gif)

2019-07-23 08:17 UTC, bolah2009 commented on index.html
> +  					<img src="image/newyorktimes.png" class="img-fluid logo" alt="new york times logo">
`REQUIRED`

Consider wrapping this logo with an anchor tag (`<a>`).

2019-07-23 08:17 UTC, bolah2009 commented on index.html
> +
`REQUIRED`

This section should contain two buttons, see below image.

![sub login preffered](https://user-images.githubusercontent.com/36057474/61694740-04aa1d80-ad2a-11e9-8ff0-f0190256ce6a.png)

2019-07-23 08:17 UTC, bolah2009 commented on index.html
> +  <img src="image/BigBang.jpg" alt="Smoking gun" class="img-fluid">
`REQUIRED`

All images and videos should be enclosed by a `<figure>` tag with `<figcaption>` that gives a description of the embedded image or video

2019-07-23 08:17 UTC, bolah2009 commented on index.html
> +    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></scr
`SUGGESTION`

It's better to delete redundant code.

2019-07-24 00:51 UTC, bolah2009 approved these changes
# Congratulations Team! :tada:

You've done an awesome Job :muscle: :clap:

#### The [page](https://raw.githack.com/MarvellousUbani/NewYorkTimes/my-feature/index.html) looks very good to me. :clap: (Plus you even add ad banner :open_mouth: ) :+1: 

Check out the code with [HTML Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2FMarvellousUbani%2FNewYorkTimes%2Fmy-feature%2Findex.html) and **increase/add the `z-index` CSS property of the navbar** to prevent the below image behaviour.

![current navbar z-index](https://user-images.githubusercontent.com/36057474/61756399-a033a080-adb3-11e9-86c3-2d270b762fea.png)

For example adding the following to that navbar class (`top-nav`)

``` CSS
.top-nav {
    .
    .
    z-index: 10;
}
```

Will result in the following image:

![preffered navbar z-index](https://user-images.githubusercontent.com/36057474/61756457-f4d71b80-adb3-11e9-96ea-0178770cb4ec.png)

#### Learn more about `z-index` [here](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index).

Good luck with your next project
Keep it up :star2:

Cheers
Bola

2019-07-24 00:51 UTC, bolah2009 commented on css/styles.css
> +    	background: #fff;
Consider adding `z-index` property here as explained in this comment.

2019-07-24 15:57 UTC, merged